name: Generate Stats Cards

on:
  schedule:
    - cron: "0 0 * * *" # 매일 밤 12시 자동 실행
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: vhost-lab
